baseURL = "https://building4.cloud/"
languageCode = "en-us"
title = "building[4].cloud"
theme = "hugo-kiera"
copyright = "Copyright &copy; 2020 - Tommi Marjomaa"

meta = "false"
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
paginate = 10

[params]
  tagline = "Beam me up, Scotty."
  description = "building[4].cloud is a personal blog site of an ops guy turning into devops guy. Posts will cover tools, tricks and lessons learned on that journey. Stack: Azure, DevOps, Powershell, Kubernetes, Infrastructure as Code."
  show_reading_time = true
  favicon = "https://building4.cloud/favicon.ico"
  customCSS = ["css/building4css_v1.css"]

[author]
    name = "Tommi Marjomaa"
    linkedin = "tommimarjomaa"
    twitter = "tommimarjomaa"
    github = "tmarjomaa"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 1